@api=http://localhost:3000/clientes 

GET {{api}}
###

POST {{api}}
content-type: application/json 

{
    "Nombre": "",
    "Id": ,
    "correo": "",
    "contraseña": ""
}

###

DELETE {{api}}/


###
PUT  {{api}}/
Content-Type: application/json

{

    "Nombre": "",
   "Id": "",
   "correo": "",
   "contraseña": ""

}
###
GET {{api}}/
